# Generated by Django 5.0.1 on 2024-02-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=150, verbose_name='Дивизион')),
                ('company', models.CharField(max_length=150, verbose_name='Предприятие')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
